spring.application.name=backend
spring.datasource.url=jdbc:sqlite:smarthome.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Auth
spring.security.oauth2.client.registration.google.client-id=128827943569-7o1ts7p6u0jgmucu3j88prlefcedro6a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

# Mail Settings (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bharathkumargmr@gmail.com
spring.mail.password=mlvz vfhg cejq lusq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvclNtYXJ0SG9tZUFwcGxpY2F0aW9uQW5kSXRNdXN0QmVMb25nRW5vdWdo
jwt.expiration=86400000

server.port=8081